# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: 'gd'

    # configure resolvers
    resolvers :
        # setup the default resolver
        default :
            # use the default web path
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: media/cache
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public/uploads'

    # your filter sets are defined here
    filter_sets :
        # use the default cache configuration
        # cache : ~

        # the name of the "filter set"
        webp_upload:
            quality: 85
            format: webp
            filters: {}
            post_processors: {}
        article_cover_thumb:
            quality: 20
            filters:
                thumbnail:
                    size: [400, 400]
                    mode: outbound 
                    focus: center

        # GENERAL_THUMBNAIL: ~
        thumbnail_small:      # mobile DPR1
            filters:
                thumbnail:
                    size: [480, 320]
                    mode: outbound

        thumbnail_medium:     # mobile DPR2 / tablette DPR1
            filters:
                thumbnail:
                    size: [960, 640]
                    mode: outbound

        thumbnail_large:      # tablette DPR2 / desktop
            filters:
                thumbnail:
                    size: [1536, 1024]
                    mode: outbound

        # BLOG_THUMBNAIL: ~
        # blog desktop thumbnail for desktop and tablette (DPR2 of 425×500)
        blog_thumb:
            filters:
                thumbnail:
                    size: [850, 1000] 
                    mode: outbound

        # blog mobile thumbnail for mobile (DPR2 of 1170×720)
        blog_thumb_mobile:
            filters:
                thumbnail:
                    size: [1170, 720] 
                    mode: outbound

        # blog cover for desktop and tablette (DPR2 of 1360×600)
        article_cover:
            filters:
                thumbnail:
                    size: [2720, 1200]  
                    mode: outbound

        # TEAM_THUMBNAIL: ~
        team_thumb_desktop:
            filters:
                thumbnail:
                    size: [720, 900]   # 360x450 en DPR2
                    mode: outbound

        team_thumb_mobile:
            filters:
                thumbnail:
                    size: [1240, 900]  # 620x450 en DPR2
                    mode: outbound

    # webp:
    #     generate: true