framework:
  rate_limiter:
    comment_posting:
      policy: 'sliding_window'
      limit: 3
      interval: '3 minutes'
    message_sending: 
      policy: sliding_window
      limit: 10      
      interval: '5 minutes' 

# policy: fixed_window : Le temps est découpé en blocs de durée fixe — par exemple, 1 minute.
# policy: sliding_window : la “fenêtre de temps” se déplace en continu plutôt que d’être découpée par minute entière.
# policy: token_bucket : Chaque utilisateur/IP a un “seau” de jetons