services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - mailhog
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  # interface web mailhog
      - "1025:1025"  # port SMTP

  # Service fail2ban
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: symfony_fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./fail2ban/data/jail.d:/etc/fail2ban/jail.d"
      - "./fail2ban/data/filter.d:/etc/fail2ban/filter.d"
      - "./var/log/security/honeypot:/var/log/security/honeypot:ro"
    environment:
      - TZ=Europe/Paris
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=1d
    restart: unless-stopped
    depends_on:
      - php-apache
     
volumes:
  db_data:
