bad_words:
  - "asshole"
  - "bastard"
  - "bitch"
  - "bullshit"
  - "crap"
  - "damn"
  - "dammit"
  - "hell"
  - "piss"
  - "shit"
  - "fuck"
  - "fucking"
  - "fucked"
  - "ass"
  - "cunt"
  - "dick"
  - "dickhead"
  - "douche"
  - "jackass"
  - "jerk"
  - "motherfucker"
  - "prick"
  - "pussy"
  - "retard"
  - "slut"
  - "whore"
  - "asshat"
  - "arse"
  - "bollocks"
  - "bugger"
  - "goddamn"
  - "holy shit"
  - "pissed"
  - "wtf"



