controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

connect_google_register:
    path: /connect/registration/google
    controller: App\Controller\SecurityController::registerWithGoogle
