name: CI Symfony MySQL

on:
  push:
    branches:
      - dev

permissions:
  contents: write 

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LOG_ENCRYPTION_KEY: ${{ secrets.LOG_ENCRYPTION_KEY }}
      MERCURE_URL: ${{ secrets.MERCURE_URL }}
      MERCURE_PUBLIC_URL: ${{ secrets.MERCURE_PUBLIC_URL }}
      MERCURE_JWT_TOKEN: ${{ secrets.MERCURE_JWT_TOKEN }}
      STRIPE_SECRET_KEY: "sk_test_fake"
      STRIPE_PUBLIC_KEY: "pk_test_fake"
      STRIPE_WEBHOOK_SECRET: "whsec_fake"
    defaults:
      run:
        working-directory: . 

    services:
      mysql:
        image: mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
        #   MYSQL_USER: ${{ secrets.DB_USER }}           
        #   MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}   
        ports:
          - 3306:3306 
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4.2
          extensions: pdo_mysql
          coverage: none

      - name: Create .env file
        run: |
          echo "APP_ENV=test" > .env

      - name: ⚙️ Create .env.test
        run: |
          echo "KERNEL_CLASS=App\\Kernel" >> .env.test
          echo "APP_ENV=test" > .env.test
          echo "DATABASE_URL=mysql://root:${{ secrets.DB_ROOT_PASSWORD }}@127.0.0.1:3306/${{ secrets.DB_DATABASE }}?serverVersion=8.0" >> .env.test
          echo "MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0" >> .env.test
          echo "MAILER_DSN=null://null" >> .env.test
          echo "LOG_ENCRYPTION_KEY=${{ secrets.LOG_ENCRYPTION_KEY }}" >> .env.test
          echo "MERCURE_URL=${{ secrets.MERCURE_URL }}" >> .env.test
          echo "MERCURE_PUBLIC_URL=${{ secrets.MERCURE_PUBLIC_URL }}" >> .env.test
          echo "MERCURE_JWT_TOKEN=${{ secrets.MERCURE_JWT_TOKEN }}" >> .env.test
          echo "MERCURE_PUBLISHER_JWT_KEY=${{ secrets.MERCURE_JWT_TOKEN }}" >> .env.test
          echo "MERCURE_SUBSCRIBER_JWT_KEY=${{ secrets.MERCURE_JWT_TOKEN }}" >> .env.test
          echo "STRIPE_SECRET_KEY=sk_test_fake" >> .env.test
          echo "STRIPE_PUBLIC_KEY=pk_test_fake" >> .env.test
          echo "STRIPE_WEBHOOK_SECRET=whsec_fake" >> .env.test
          echo "GOOGLE_ID=fake-google-id" >> .env.test
          echo "GOOGLE_SECRET=fake-google-secret" >> .env.test

      - name: 💾 Cache Composer
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer/cache
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: 📦 Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      # - name: Get MySQL container ID
      #   run: |
      #     MYSQL_CONTAINER_ID=$(docker ps -q -f "name=mysql")
      #     echo "MySQL container ID: $MYSQL_CONTAINER_ID"
      #     docker logs $MYSQL_CONTAINER_ID 
      

      - name: 🛠 Run Doctrine migrations
        run: |
          APP_ENV=test php bin/console doctrine:database:create
          APP_ENV=test php bin/console doctrine:schema:create
        # APP_ENV=test php bin/console doctrine:migrations:migrate --no-interaction
        # APP_ENV=test php bin/console doctrine:database:drop --force --if-exists

      - name:  Lint YAML, Twig and Container
        run: |
          php bin/console lint:yaml config
          php bin/console lint:twig templates
          php bin/console lint:container

      - name: ✅ Run Tests
        run: APP_ENV=test php bin/phpunit

      - name: ⬆️ Merge dev into test if tests pass
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch --all
          git checkout test
          git merge origin/dev --no-ff -m "CI: merge dev into test"
          git push origin test